IF NOT EXISTS (SELECT  1 FROM SYS.TABLES WHERE NAME = 'Category')
	BEGIN

		CREATE TABLE Category (
			Id INT NOT NULL IDENTITY (1, 1)
			CONSTRAINT PK_Category_Id PRIMARY KEY (Id),
			Name VARCHAR(45) NOT NULL
			CONSTRAINT DF_Category_Name DEFAULT(''),
			Created DATETIME NOT NULL
			CONSTRAINT DF_Category_Created DEFAULT('1900-01-01 00:00:00.0'),
			CreatedBy INT NOT NULL
			CONSTRAINT DF_Category_CreatedBy DEFAULT(-1),
			Updated DATETIME NOT NULL
			CONSTRAINT DF_Category_Updated DEFAULT('1900-01-01 00:00:00.0'),
			UpdatedBy INT NOT NULL
			CONSTRAINT DF_Category_UpdatedBy DEFAULT(-1)
		);

	END;
GO