IF NOT EXISTS (SELECT  1 FROM SYS.TABLES WHERE NAME = 'Coupon')
	BEGIN

		CREATE TABLE Coupon (
			Id INT NOT NULL IDENTITY (1, 1),
			Code VARCHAR(45) NOT NULL
			CONSTRAINT DF_Coupon_Code DEFAULT(''),
			DisccountAmount FLOAT NOT NULL
			CONSTRAINT DF_Coupon_DisccountAmount DEFAULT(0),
			MinAmount FLOAT NOT NULL
			CONSTRAINT DF_Coupon_MinAmount DEFAULT(0),
			Created DATETIME NOT NULL
			CONSTRAINT DF_Coupon_Created DEFAULT('1900-01-01 00:00:00.0'),
			CreatedBy INT NOT NULL
			CONSTRAINT DF_Coupon_CategoryId DEFAULT(-1),
			Updated DATETIME NOT NULL
			CONSTRAINT DF_Coupon_Updated DEFAULT('1900-01-01 00:00:00.0'),
			UpdatedBy INT NOT NULL
			CONSTRAINT DF_Coupon_UpdatedBy DEFAULT(-1)
		);

	END;
GO